[profile.default]
solc-version = "0.8.21"
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 1

# See more config options https://github.com/foundry-rs/foundry/tree/master/config